version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
         name: Decrypting deployment key
         command: openssl aes-256-cbc -d -md sha256 -in signing/publish/play-store-deployment-encrypted.json -out signing/publish/play-store-deployment-64.json -k $KEY
      - run:
         name: Decrypting deployment key from base 64
         command: base64 --decode signing/publish/play-store-deployment-64.json > signing/publish/play-store-deployment.json
      - run:
          name: Decrypting release build key
          command: openssl aes-256-cbc -d -md sha256 -out signing/release/salads-release-key-64.jks -in signing/release/salads-release-key-encrypted.jks -k $KEY
      - run:
          name: Decrypting release build key from base 64
          command: base64 --decode signing/release/salads-release-key-64.jks > signing/release/salads-release-key.jks
       - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#          name: Run Tests
#          command: ./gradlew lint test
#      - store_artifacts:
#          path: app/build/reports
#          destination: reports
#      - store_test_results:
#          path: app/build/test-results
      - run:
          name: Deploy Release
          command: ./gradlew publishApkRelease -PdeployJsonFile="../signing/publish/play-store-deployment.json" -PkeyAlias="$RELEASE_ALIAS" -PkeyPassword="$RELEASE_PASSWORD" -PstoreFile="../signing/release/salads-release-key.jks" -PstorePassword="$RELEASE_STORE_PASSWORD" -PisCiBuild="$CI"